### ISSUE TITLE
Ken Burns effect does'nt work in screensaver mode

### ISSUE THREAD

**Issue by teiseva2000** [mvysny/photocloud-frame-slideshow#124]
Hi,
I set the Kne Burns effect but when the screen saver is started on my Android TV The effect doesn't work.
Could you help me?
BR
Andrea

**Comment by mvysny** [comment]
Hi Andrea,
  I assume you're using Chromecast to cast your phone into an Android TV. In such case the Ken Burns effect is unfortunately disabled on the Chromecast device. The reason is that Chromecast doesn't support transferring the image to the TV and animating it there. Instead, Chromecast simply streams a scene produced on the phone as a video, with a very low bandwidth. Animating an image with Ken Burns effect in Chromecast would produce terrible pixelation, as if watching a video with insanely low bitrate.

I know that certain apps run natively on Chromecast (e.g. Youtube or Netflix), however this is only a proprietary closed set of applications hand-approved by Google from big vendors. There is no way to add a PhotoCloud app into Chromecast.

Please let me know if this answers your question.

**Comment by teiseva2000** [comment]
Thanks a lot for your reply. 
I haven't the chrome cast. I have a Sony Bravia Android TV. I download on my TV your app. 
When I try the app from Gallery the filter work fine instead when it start from Screensaver doesn't work. 
Any suggestions? 
Br

⁣Andrea

Ottieni BlueMail per Android ​

Il giorno 7 apr 2020, 14:37, alle ore 14:37, Martin Vysny <notifications@github.com> ha scritto:

**Comment by mvysny** [comment]
Ah, right, I misunderstood, you were talking about the Daydream. I've reviewed the code and you're right - the Ken Burns effect is not applied to the DayDream. It's definitely a bug, luckily that should be fixable rather easily.

**Comment by teiseva2000** [comment]
Great 
Many thanks for yot reply. 
I will wait your update. 
Br

⁣Andrea

Ottieni BlueMail per Android ​

Il giorno 8 apr 2020, 09:37, alle ore 09:37, Martin Vysny <notifications@github.com> ha scritto:

**Comment by mvysny** [comment]
Thank you for your patience, I've finally managed to fix this issue. Day Dream now applies Ken Burns effect (if it is enabled in the Settings).

This fix will be present in PhotoCloud 1.13.17 (sorry, no estimate on release yet, but probably some day this week).

**Comment by teiseva2000** [comment]
Thanks a lot 
Br

⁣Andrea

Ottieni BlueMail per Android ​

Il giorno 15 apr 2020, 07:30, alle ore 07:30, Martin Vysny <notifications@github.com> ha scritto:
