### ISSUE TITLE
Add option for "zoom"-scale only for Landscape-Pictures

### ISSUE THREAD

**Issue by Dax88** [mvysny/photocloud-frame-slideshow#149]
Hi, perhaps you can add an option to aply the Scale Type "zoom" only for landscape-pictures.
In my case i use a tablet in landscape mode. If I enable the scale type "zoom", my landscape-pictures are fine but my portrait-pictures are zoomed in to much.
The same option would be grate for the "Panorama pan" effect - i just want to enable this effect for my landscape photos. 
It is ok if there are black bars left and rigth of my portrait pictures...

**Comment by mvysny** [comment]
> Scale Type "zoom" only for landscape-pictures.
In my case i use a tablet in landscape mode. If I enable the scale type "zoom", my landscape-pictures are fine but my portrait-pictures are zoomed in to much.

Would enabling the "Fit" Scale Type resolve the issue?

> The same option would be grate for the "Panorama pan" effect 

Would you like to have a setting to only enable "Panorama pan" effect for landscape photos, and "Static" Effect + "Fit" Scale Type for portrait (so that they don't scroll vertically)?

**Comment by Dax88** [comment]
> Would enabling the "Fit" Scale Type resolve the issue?

With the "Fit" Scale Type enabeled i have black bars left and right (because the aspect ratio is different to the screen). 

> Would you like to have a setting to only enable "Panorama pan" effect for landscape photos, and "Static" Effect + "Fit" Scale Type for portrait (so that they don't scroll vertically)?

Sounds good!

**Comment by mvysny** [comment]
Excellent! Now I need to figure out how to make this configurable in the easiest way :-)

**Comment by mvysny** [comment]
Implemented in PhotoCloud 1.14.2
