### ISSUE TITLE
Port to ios and M1 Macs

### ISSUE THREAD

**Issue by blackest** [mvysny/photocloud-frame-slideshow#150]
Hi Thank you for making the photocloud frame slideshow. 
I was glad to purchase it, my old android tablet a nook hd runs it slowly but surely and only once out of memory so far. :)
I even considered buying a newer tablet but then realised i couldn't get a decent screen and a snappy android tablet for a reasonable price. 

I have pretty much every photo I have ever taken stored in lightroom and they are backed up on a nas, and putting photocloud frame slideshow at the root of that folder structure results in seeing good memories and some of the time, good photos. I think there are around 30,000 so having them drift by in the corner of the room is nice relaxing not too repetitive and gives the tablet something to do besides being an alarm clock.  I have even automated it somewhat with the psu being plugged into a smart plug turning it off and turning it on starts up the slide show.  I especially like the folder/ picturename so I can open it up in lightroom especially when it "ken burns" the photo into an interesting crop. 

I had a look in the Ios store to find something similar and nothing is as good as your app. On the m1 macs ios apps can be a window or full screen and it would be excellent to have your app running either in the corner or filling a display. 

I think people would pay for your app on ios and the new M1 Macs and old iPads would make a great photo frame having a nice resolution display and plenty of processing power and ram , which to be honest is where android devices tend to fail. 

You have made an excellent app that would brighten anyone's day, it's so nice to be able to look back at normal times and look forward to getting together with friends and family again.

Would you consider a port to ios?

**Comment by mvysny** [comment]
Hello, thank you so much for your kind words, I'm really happy that you like PhotoCloud ;) I'm really puzzled by the fact that there's no decent Photo Frame software for iOS :thinking: Unfortunately I do not use iPad myself and so I can not really recommend a good Photo Frame software. Looks like a hole in the market...

Unfortunately, porting PhotoCloud for iOS is an enormous undertaking: I would have to learn to develop using an unfamiliar programming language (Swift) on an unfamiliar dev env (XCode); I'd have to purchase a Mac computer since XCode only runs on Macs; I would then have to painstakingly port all of the code (including all cloud client libraries) to iOS... And, unfortunately, I have no spare time nor mental energy to perform such a huge task. The problem is that even though apps on iOS tend to earn much more money than on the Android platform, I don't think it's enough for me to ditch my job and start working on this, no matter how much I'd love to.

I am in fact really unhappy with the Android development environment (the SDK is honestly a piece of turd, and Google charges 30% on top of that); I'm sure switching to iOS would actually be amazing experience. But, unfortunately, it's not possible.
