### ISSUE TITLE
Nextcloud Configuration?

### ISSUE THREAD

**Issue by chr2k** [mvysny/photocloud-frame-slideshow#158]
I found this App in Play Store. I want to test it. 

But i fail with the Nextcloud Configuration. Sometimes if i want to connect the App tells me Error 401, 405, and so on. Never get a connection.

Any Ideas?

Thank you.

**Comment by mvysny** [comment]
Hi, Nextcloud communicates via the WebDAV protocol which uses HTTP Authentication underneath. So those error codes actually come from the HTTP protocol itself and the meaning is as follows:

* 401 UNAUTHORIZED: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
* 405 METHOD NOT ALLOWED: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

The first one definitely means that the username or password is either incorrect or missing. Please verify that the username and/or password you provide is correct.

The second one is intriguing but it could be caused by the first issue actually. Therefore, please try to resolve the first issue first, before taking a look at the "405" issue.

**Comment by chr2k** [comment]
THank you.

No i get a "400" Error.

Error: java.io.IOException: list / failed: 400

**Comment by mvysny** [comment]
HTTP 400 stands for "Bad Request". Not sure what's so bad about a directory listing request though :-D

However, according to https://help.nextcloud.com/t/request-failed-bad-request-400/35037/2 it sounds modifying the list of trusted domain to include your domain. Please see more here: https://help.nextcloud.com/t/howto-add-a-new-trusted-domain/26

**Comment by mvysny** [comment]
Closing as stale; please reopen and provide necessary information if need be.
