### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by JeanneZuidhorn** [mvysny/photocloud-frame-slideshow#161]
Goodmorning,

View days ago I bought Photocloud. A super program to automatically show my mother the outside world.

I paid Google €3.99, but it doesn't work. I keep seeing the screen to buy the program. I asked Google to refund my money but they didn't. I just had to contact the developer. (It's not easy, to be honest.)

Can you help me?

(maybe this isn't the right place to get a solution for this, but I don't really know where else to go. )

**Comment by mvysny** [comment]
Hi Jeanne, this is the correct place :+1: 

I'm sorry to hear about your troubles. Actually Google is in charge of the payments and refunds (since they charge 15% for that service and the payments are handled by Google and the "Google Play" app store); Google ditching their responsibility like that is really infuriating. But they're the monopoly so they can suck however they want I suppose :/

There is a list of [FAQs here](http://www.android-photo-frame.eu/faq.html), please try to follow steps outlined in "Purchase not restored after reinstall".

**Comment by JeanneZuidhorn** [comment]
Thanks for your quick response. The world isn't as bad as I first thought
;-)

I will of course go through the steps, because I want it to work.
But I do hope that you don't let things figure out endlessly, if there is a
more easy solution.



Op do 12 aug. 2021 om 09:09 schreef Martin Vysny ***@***.***>:

**Comment by JeanneZuidhorn** [comment]
![Screenshot_2021-08-16-18-16-37-492_com google android gm](https://user-images.githubusercontent.com/88807779/129738001-559efe2d-ebf2-4959-96cc-5d6601f780d5.jpg)
![IMG_20210816_181348](https://user-images.githubusercontent.com/88807779/129738052-6403a6ea-34d3-4396-b6b2-359c54b58885.jpg)


Hello again,

I factory swiped my tablet, I install again.
What I see is a true near the API, a false near the unlocked Nagging and true near the Daydream thing 
What went wrong?
Did I purchased the wrong item? Can I do anything to correct this?
I will send you my purchase and print-screen
Can you give me the right instructions?

Thanks

**Comment by mvysny** [comment]
Hi, yeah it sounds like you have bought the incorrect item. Just let me know and I'll try to refund.

**Comment by JeanneZuidhorn** [comment]
Please, but I can buy the other item, I'm not bankrupt if a pay more.
Better expensive then not for sale!
Just let me know how to proceed

**Comment by mvysny** [comment]
No problem! There are two Purchase options when you open the PhotoCloud Settings:
* Purchase
* Purchase Daydream/Screensaver

You accidentally purchased the latter one, while you need to purchase the former one, simply titled "Purchase". There's a summary just below the option stating "Supports the author and removes the nagging dialog - thank you! :)" which refers to the Nagging Dialog Removal :)

However, it's true that the caption should be a more informative "Purchase Remove Nagging Dialog" instead of just "Purchase" - I'll update the caption.

**Comment by JeanneZuidhorn** [comment]
Oké, but what did I buy with the other option? Daydream screensaver? It is
a screensaver already with all the different foto?

Op do 19 aug. 2021 07:30 schreef Martin Vysny ***@***.***>:

**Comment by mvysny** [comment]
The Daydream purchase unlocks the PhotoCloud integration with "Android Daydream", see https://www.samsung.com/my/support/mobile-devices/what-is-the-daydream-feature-and-how-do-i-use-it-on-my-samsung-galaxy-s5/ for more details. In short, if you don't use Android Daydream, then the "Daydream" PhotoCloud purchase option won't add any new features for you.
