### ISSUE TITLE
SMB access / and prev/next sometimes not working

### ISSUE THREAD

**Issue by Brun059** [mvysny/photocloud-frame-slideshow#17]
Thank you for your reply on 27 June. The syntax for entering SMB drives is confusing. I expected "_smb://192.168.0.6_" , or "_192.168.0.6_" . neither worked. The error msg finally triggered me, it prefixes with **smb:/**, hence I entered  **/192.168.0.6** . that did not give an error msg. 
I still cannot browse the folders though (have tons of subfolders)  

but finally got it to work, thanks. 

I tried pretty much every slideshow app I could get my hand on. The criteria I have 

1. ok : SMB access  (ideally more than one source or folder, ideally browsing from root and selecting folders
2. ok : display pics from recursive subfolder
3. ok : shuffle/random display 
4. ok : display full folder and filename, at least when tapping a pic. (the foldername has all the context) 
5. nope : enable zoom (strangely, some otherwise good apps don't, neither does Photocloud)
6. nope : thumbnail map - and open google maps upon tapping it 
7. buggy : slide for prev/next 
    (Photocloud does in some circumstances, but not after I've looked at a pic's detail in random mode)
8. open : reading the rotation meta data (need to check further)

- nice to have : 
     a. autostart when plugged in (or at least keep screen awake) (ok)
     b. and staying on when I grab the tab as I want to see THAT picture (other apps disappear when unplugged) (need to try)
     c. ability to delete files (on server) 
     d. custom slideshow delay, e.g. 2 mins  ;-)

and thank for sour support. it's appreciated, VERY much (brings my family memory back to live and replaces a 10 year old ubuntu minibook with FEH)

**Comment by mvysny** [comment]
Hi, thanks for letting me know. This is weird: I have just tried to create a samba stream; I have just entered `192.168.100.12` into the "Computer Name" field, and it worked - it asked for username/password and then I was able to browse the samba share.

Samba is a proprietary Microsoft protocol which has not been open-sourced; I'm using JCifs which was created by reverse-engineering of the protocol. Maybe it has a bug - in that case please feel free to report it to the JCifs team.

PhotoCloud saves bandwidth and both cache memory and phone memory by downscaling the images to the display resolution. That's why zoom is impossible with the current design. There are currently no plans to change that.

Thumbnail map - please open a new bug report with more details.

Slide for next: sorry, just slide to prev 5 photos is implemented.

Ability to delete files - perhaps I can implement it for Samba only. Please create a bug report for that.

Custom slideshow delay - sure, no problem ;) Just open a new feature request and list all additional options which you would like to have.

**Comment by Brun059** [comment]
Prev/next  scenario : 
full screen - tab (little arrow) >prev/next work :-)  .  tab again for full screen ok ; Tab again to swipe: BLACK screen :-(
have to wait till picture refreshes again, then it prev/next work.

**Comment by mvysny** [comment]
Reproduced, thanks!

**Comment by mvysny** [comment]
Prev/next: Fixed in 1.8.1. For other issues, please open a separate bug reports for them.
