### ISSUE TITLE
Slideshow gets stuck after a couple of hours

### ISSUE THREAD

**Issue by Powersurge** [mvysny/photocloud-frame-slideshow#172]
I have an Amazon Fire HD 8 tablet that I wasn't using so I decided to flash Lineage OS on it with only this app running and connected to my Nextcloud account. After about an hour or so the slideshow freezes, but not always on the same photo. I initially thought that it might be a weak wireless connection that was causing the issue, so I boosted the signal on my router, but that didn't fix the problem. Could it be that my tablet doesn't have enough RAM to run this app? When the slideshow gets stuck, I can usually exit out of the app, but the tablet seems very unresponsive until it's rebooted. Does anyone have any thoughts about what can be causing the issue that I am having? Thank you in advance.

UPDATE: I just found some info on the website about memory and crashes. Will do some more testing and will report back.

**Comment by mvysny** [comment]
Hi, thank you for reporting & super thanks for doing the research :) If the tablet itself feels unresponsive, perhaps the bug is actually present in the OS itself, and PhotoCloud just happen to trigger it somehow. A good workaround would be to decrease the memory usage: please try following https://www.android-photo-frame.eu/faq.html the "Memory & Crashes" section.

**Comment by Powersurge** [comment]
Well, I tried enabling "Load with Half Resolution" and let it run overnight and it was stuck by the morning. I think the problem is with the tablet though, because I then tried doing a factory reset and the tablet froze up on me! I'll try this app out again when I can get my hands on another tablet. Thank you for your help! :)
