### ISSUE TITLE
OneDrive Exception

### ISSUE THREAD

**Issue by kriscs1** [mvysny/photocloud-frame-slideshow#45]
After displaying a number of photos from a photostream of OneDrive, I get the error:

sk.baka.photoframe.util.ioexceptionwithcause: com.onedrive.sdk.core.eclientexception: error during http request.

It occurs after displaying a number of photos correctly.

**Comment by mvysny** [comment]
Hello, thanks for letting me know. Usually these kinds of errors are reported to my console, but there are no such reports... Can you please provide more data, for example a screenshot?

**Comment by kriscs1** [comment]
Here's a photo: https://imgur.com/a/YXXux

**Comment by mvysny** [comment]
Huh that's weird. Typically OneDrive exceptions tend to provide a lot more information. For example see a screenshot at #35 .

Would you be willing to connect the device to your PC and obtain the log from the device? The exception should be logged there, including the stacktrace.

**Comment by kriscs1** [comment]
Unfortunately, the tablet doesn't appear have a USB socket. It is a wall mounted tablet that only has an ethernet port (PoE) on the back.

**Comment by mvysny** [comment]
I see. Never seen such Android device before :-) Unfortunately then I do not have enough information to proceed. I know that OneDrive works for other uses, so perhaps this issue is somehow connected to your device only?

Can you please try to kill the "PhotoCloud" app, and/or reboot the Tablet? That should hopefully report the issue to my console, since all errors are reported when the app starts anew.

**Comment by kriscs1** [comment]
I just rebooted the tablet.

**Comment by mvysny** [comment]
Hmm, still no error report on my Crashlytics console. What a letdown. However, perhaps this is the issue we are looking for? If yes, then I'm afraid it's Microsoft responsibility to fix it.
https://github.com/OneDrive/onedrive-sdk-android/issues/129

**Comment by kriscs1** [comment]
Bummer. No way to detect the error message and force the app to restart or similar?

**Comment by mvysny** [comment]
Let me look at the Crashlytics API. Perhaps there is a way to send the error immediately to me.

**Comment by mvysny** [comment]
Nope, there isn't. What a letdown. More info here: https://docs.fabric.io/android/crashlytics/caught-exceptions.html
It's easy to force the app to restart - just open the Task List (the Square Button on my phone) then drag the app towards the rightmost corner - that should kill the app. Do this immediately after you see the exception; next time the app starts the error should be reported immediately. Or not - Crashlytics is weird and the error report can not be forced by other means to actually crashing the app. 

In the worst case I'll add such a button so that the bloody exception is reported.

**Comment by mvysny** [comment]
What version of Android do you have? Is it perhaps Android 4.2 or older?

**Comment by kriscs1** [comment]
It's 4.4.2

**Comment by kriscs1** [comment]
And yes, newest version of photocloud

**Comment by mvysny** [comment]
This could be fixed along with #6 - in case of error OneDrive will simply be polled until it comes back to mind and starts responding properly. Closing as fixed, please reopen if the error persists.
