### ISSUE TITLE
Show most recent (Moments, filter based on date)

### ISSUE THREAD

**Issue by theQuicker1** [mvysny/photocloud-frame-slideshow#50]
Delete or stop showing photos that have been on the slideshow for a user-selected amount of time.  For example, the app stops showing the photos that have been in the feed for 2 months (except those photos marked as favorites using an in-app favorites button or maybe saving the favorites to a device folder).  

This is helpful for families who like to keep adding photos to a folder of slideshow pictures, but only want the most recent photos to show.  Other considerations might include "Show most recent [user-defined number] of photos" or "Show only photos from the last [user-defined number of] weeks (but keeping at least 50 photos in the slideshow at all times)".

**Comment by mvysny** [comment]
The easiest option is just to filter out photos older than 2 months. However, that could potentially cause all photos to be filtered out, causing Slideshow to simply show "No photos" which is very bad. Maybe some kind of photo sorting that would prioritize newest photos somehow? However, to implement that properly, that would require a full scan of all photos in the filesystem and sorting that list in-memory, which may eat up all memory. Also, that would delay the initial showing of the Slideshow until the entire fs has been crawled which is definitely something we want to avoid.

It could be possible to cache the file list to a database, however the filesystem is a very lively thing, prone to change, so that database would have to be constantly updated.

However, there could be a way. If the folders in the FS would be named as, say, 2017-06 (year then month), it would be easy to start with the newest folders and continue crawling until 50 photos has been reached, then restart the whole Slideshow. That would show 50 newest photos. However this requires a proper naming scheme established by the user. Unfortunately, there is no other way - filesystems typically lie about the last modification date of a folder and often it is not clearly defined what that even means (is it creation date? last rename date of the folder itself? last operation of any kind inside of the folder? recursively?).

**Comment by theQuicker1** [comment]
The naming folders option is far too much strain on the user. I know my sisters would never add anything.

For filtering out photos older than a certain date, to overcome the possibility of filtering out all photos (say if none were added in the last 2 months), could you add something like, "If there are less than 50 pictures matching this query, search from 3 months, 4 months, ..., all photos." 

It would probably be good to always add in say 30% old photos randomly anyway.

Thinking about ever changing lively file systems, one thing I really like about this app is that it adds new photos to the slideshow almost as soon as I upload them!

**Comment by mvysny** [comment]
Now the problem is to obtain the proper creation date. The only true creation date is stored in the EXIF data; however reading a photo just to obtain the EXIF is a very expensive operation.

On the other hand, the cloud storage (a file-oriented cloud storage such as Dropbox which generally do not care about the file types) typically provides an upload date, when the file has been uploaded to the cloud. However, that may be days or even weeks after the photo has been taken, depending on how often you upload/synchronize photos.

I wonder if this discrepancy wouldn't render the filtering logic useless...?

**Comment by theQuicker1** [comment]
I think that the upload date will work just fine (at least for my family). I would guess that most people uploading pictures for a frame would do it sooner rather than later after an event. If they habitually wait weeks, then they will want to take that into consideration when choosing how many days "old" will be, or not use this "Display only recent photos" feature.
Yes, I can see the problem with a large upload of old photos, but after a year, that should sort itself out since new pictures will start flowing in and take priority.  

I do like the idea of adding in old pictures with weighted priority given to pictures near that time of year (like Google Photos annoyingly does).

How many photos do you want to show? [100]
Show photos not older than [90] days.
What percentage of photos older than 90 days do you want to add to the slideshow? [50]% (chosen randomly, weighted for time of year, shown according to preference (random/ordered))

Speaking of the random/ordered setting, out of curiosity, is the randomizer true random, or does it go through all the pictures before showing the same one again?

Slightly related to this thread:
It seems like this is already implemented in the background which is awesome: "Show new uploads immediately" (then after displaying them once, they get shown in the same way as everything else).

**Comment by mvysny** [comment]
> Speaking of the random/ordered setting, out of curiosity, is the randomizer true random, or does it go through all the pictures before showing the same one again?

It goes through all the pictures. When you start the slideshow, PhotoCloud starts the discovery process of all photos, building a pool of photos. That pool is gradually exhausted as the photos are shown; the photos are taken randomly from the pool. When all photos are discovered, the discovery stops. When the pool is exhausted, the discovery runs again and the whole process is repeated. This guarantees that all photos are streamed with the same probability.

> It seems like this is already implemented in the background which is awesome: "Show new uploads immediately" (then after displaying them once, they get shown in the same way as everything else).

Yup, new photos are picked up automatically as the discovery is reinitiated.

> How many photos do you want to show? [100]
Show photos not older than [90] days.
What percentage of photos older than 90 days do you want to add to the slideshow? [50]% (chosen randomly, weighted for time of year, shown according to preference (random/ordered))

This "minimum number of photos" is problematic since I would have to discover all photos to check if there is at least 100 photos satisfying those criteria. That would delay the initial slideshow immensely.

I propose to start simple for now and drop the "min number of files" criteria. If no photos will match, the Slideshow will simply show "No Photos" and the user needs to increase the date range :-D I will keep thinking on how to solve this.

I will however add the percentage idea, I quite like that.

**Comment by mvysny** [comment]
Implemented in PhotoCloud 1.10.10

**Comment by theQuicker1** [comment]
I do not think I understand the new Moments settings. ... No, now after studying it for a while, I think I get it.  The two setting essentially allow this: Show photos from the last week, and photos older than a month, but not those in between (a gap).  I think what you accomplish with two date settings can be done with one (I don't see a need for creating a gap).

It may be easier to understand the settings if you use phrases like "older than" instead of "not newer than".

_The following are my suggestions that I should have added a week ago. It is essentially a different way of implementing this. Maybe you will like this solution better, maybe not. I just wanted to share my thoughts. The final decision is, of course, up to you._

I am probably thinking of the discovery all wrong.  I am imagining that the API gives you a list of all files, then you can take that list and filter it to only the images, then sort those by date.  If there are actually not lists that can be sorted quickly, then, at least to my thinking, things get much more complicated, and the rest of this post won't be much help.

>>How many photos do you want to show? [100]
Show photos not older than [90] days.
What percentage of photos older than 90 days do you want to add to the slideshow? [50]% (chosen randomly, weighted for time of year, shown according to preference (random/ordered))

> This "minimum number of photos" is problematic since I would have to discover all photos to check if there is at least 100 photos satisfying those criteria.

Sorry, I was not very clear.  I meant that number to be a maximum, not a minimum.  Will it work to implement it as a maximum?  

I don't know a lot about programming so in my head I imagine generating a list of photos to slideshow like this: 

- Generate a list of all photos from root folders.
- If list is less than 100, show them all.
- If list is more than 100, sort by date. For the group of photos within 90 days randomly pick 50 photos (50% of 100), and for the photos in the list older than 90 days, randomly pick 50 more (to meet desired 100). If there are not 50 "recent" photos, fill the space with "old" photos. Take all chosen photos and randomize (assuming user selected to show photos randomly).  

Now that we have created a list of what we want to display, start downloading (or pulling from cache).
While this is processing in the background, show cached photos.  With this "recent photos feature" enabled, it may take longer for show to start if there are no cached files, but if you are using the app with this enabled, you are probably not in a hurry to start it anyway (e.g. a frame that will be on all day long).

Again, this may be me misunderstanding how things are implemented, but it seems like these ideas are already being implemented as follows. 
- If no WiFi, show cached. 

>When all photos are discovered, the discovery stops. When the pool is exhausted, the discovery runs again and the whole process is repeated.

- With wifi, when slideshow starts, there is a brief delay as it does its "Info: crawling ..."  Then, when the pool is exhausted, the discovery runs again. However, there is no delay this time. (So I imagine it is doing the discovery in the background somehow.)

>If no photos will match, the Slideshow will simply show "No Photos" and the user needs to increase the date range

The percentage idea solves the date range problem.  But, only if there is a maximum set (e.g. [100]).  Then, we know how many we want.

How does your current implementation of the percentage account for more photos turning "old"? Say I have 10 new photos and 1000 old photos.
Is the 100% setting to be able to show only old photos?

Many thanks for working on this feature.

**Comment by mvysny** [comment]
> Generate a list of all photos from root folders.

That's the core of the problem. We can't do that. That would delay the start of the slideshow tremendously. That implies that we can't continue with the algorithm as you suggested, since we do not know how many files there are, thus I don't know how to evaluate the condition "if the list is less than 100".

**Comment by theQuicker1** [comment]
> when a first suitable image falls off the API I'll try to load it immediately, so that the initial delay of showing the first picture is the smallest possible.

I like that solution.  Could it start that way, then revert to the curated slideshow after the list generation is complete?  Put another way, start with any random pictures until the server list is generated, then begin showing the slideshow list of the selected moments-based pictures.

**Server list:** list of all pictures available to show
**Slideshow list**: list of pictures (taken from server list) we want to show

Maybe the API will not allow this. Can the server list be saved to memory, then updated with new pictures as they are uploaded, and cleaned up when a file on the list is requested but not available? This might save list generation time.

**Comment by mvysny** [comment]
Unfortunately the list can not be saved to memory - if the photo number is too great the memory will be filled and the app will crash. The list is however saved to a database (see #56 for more details); however it is immediately consumed by the slideshow. 

The solution would be to build two (or more) lists, filtered with different filtering options. Only the first list would be consumed by the slideshow; if the first list is consumed and is found to be too short, the slideshow may switch to consume the second list.

Inventing an algorithm is easy; implementing it in a thread-safe manner and testing it is another thing, and this requires lots of time and manpower, both of which I currently lack. Anyway, please open a new feature request to keep track of this improvement.
