### ISSUE TITLE
Possible to Add Support for Network Connection Error?

### ISSUE THREAD

**Issue by mouser2017** [mvysny/photocloud-frame-slideshow#6]
First, let me say that I think it is great that I can delete a photo from OwnCloud (or add one) and it automatically updates.  The syncing is fantastic.  

However, when the connection goes down, the slide show crashes essentially.  

Would it be possible to add support to check for the connection and if there is a connection error, attempt to continue with the cached files until the next connection check that yields a successful connection?

I'm thinking of using this across the Internet where a connection could go down.  After an outage, right now it would just stop working.  This feature could allow it to automatically reconnect and re-sync at some point once connectivity has been restored.

**Comment by mvysny** [comment]
Thanks! Actually there is such a code: when the android wifi goes down, photocloud will switch to the "cached images only" mode. But I haven't anticipated the case when the WiFi is okay but the server goes down (maybe briefly only, for a computer restart). Sure, photocloud should handle this gracefully. I'll think of something.

Maybe in such case, an information "can't connect to the server, showing cached images" should be shown in the slideshow, so that the user is informed.

**Comment by mvysny** [comment]
Maybe I should add a simple probe method to each FS which will simply ping the server whether it's alive. If the ping fails after, say, 5 seconds, then the server is considered down, and cached images should be shown. This needs a periodic server re-ping whether it has come up. Also if WIFI is down then there is no need for ping since there's no network.

**Comment by mvysny** [comment]
Partly fixed by #41 - the slideshow will wait a bit until the server comes back online. The slideshow unfortunately won't continue with cached images (instead it will wait for the server to come up), but at least it won't stop immediately.

**Comment by mvysny** [comment]
Implemented. If the network fails, the slideshow switches for that particular stream into the "cached" mode. In that mode, only the cached images are shown, and in the background the stream is pinged. If the stream comes back online, the "cached" mode ends and the stream is again polled for images.

Note that the stream is pinged rapidly at first, but the ping rate gradually decreases, to avoid unnecessary load on the server. The max duration between pings is set to 10 seconds, so it may take up to 10 seconds for the PhotoCloud to notice that the stream is up.

Implemented in PhotoCloud 1.10.
