### ISSUE TITLE
Customize file name format in the EXIF widget

### ISSUE THREAD

**Issue by amingle4** [mvysny/photocloud-frame-slideshow#65]
Reference: [https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/photocloud-frame/t9FZgubq59E](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/photocloud-frame/t9FZgubq59E)

Suggestion to add different customization options for displaying text or other EXIF options.

Example: Where it currently displays the parent directory, there would be 3 options:
1. The current option (parent directory) [folder2]
2. The parent directory + filename [folder2/imapicture.jpg]
3. The last XXX characters of the full path (the appropriate number of characters would have to be determined) [.../folder1/folder2/imapicture.jpg]

Additionally, could consider: customizations (checkboxes/order choices) for each corner of the screen.  For instance, top left of the screen could be the Date Taken, bottom left could be filepath/file info (like it is now), etc.

**Comment by jankete** [comment]
It would be great, if we could choose which EXIF is shown and how the text is formatted.

**Comment by mvysny** [comment]
@jankete regarding the EXIF tag please feel free to open a new feature request. It would be great to provide concrete suggestions (e.g. which EXIF tags to pick from since there is 50+ of EXIF tag types https://developer.android.com/reference/android/media/ExifInterface.html )

@amingle4 I'm thinking two switch settings:
1. Show file name [yes/no], defaults to no
2. Show full path [yes/no], defaults to no which would just show the parent directory

Ellipsis (prepending text with `...`) would simply be always enabled, to truncate long paths (or long parent directory names).

**Comment by amingle4** [comment]
What you describe sounds good to me.

**Comment by amingle4** [comment]
For EXIF, date taken is really the one I'd want to see. But that's a personal preference.

**Comment by mvysny** [comment]
The file name format is now customizable as agreed. Fixed in 1.11. Regarding the EXIF support - please open a separate feature request for that - thanks!

**Comment by amingle4** [comment]
Works well - thank you sir.  The visible text is a little short at times, but it's much nicer for me to see even a portion of the parent directory name.
