### ISSUE TITLE
AndroidTV: User Design Experience

### ISSUE THREAD

**Issue by nascentt** [mvysny/photocloud-frame-slideshow#76]
Many thanks for the AndroidTV Support, however I still find the process of adding a samba share via remote control on an Nvidia Shield a painful process.  I spent about 10 minutes trying to add a share because first it fails to find the server and points to the wrong ip (this no longer happens during typing the share name, but after pressing the go button).  Then the mix of using the android onscreen keyboard is also quite awkward.  I typed my sharename and press next, then it presents a keyboard again, but I didn't have anything more to type, so I tried pressing back to hide the keyboard and it exited out back to the main screen. So I tried again, this time I press next, then finish at the next keyboard, and it removes the keyboard and shows the screen behind it, So then you need to manually navigate to the go button, but the visual highlight when selecting that control is so subtle its hard to know when you're selecting it.

Once finally selecting the go button, it requested credentials, which I typed out, then I press next and finish and it exit back to the main screen.  I went through the process again, and realised it's because cancel is highlighted by default not done, so when you press finish on the keyboard after entering the credentials it thinks you want the dialog's cancel button so quits.

I basically had to get a combination of knowing when to use the on screen keyboard, when you back out of it and navigate the controls using the remote control, then it finally worked.

Just wanted to inform you of this as it may put users off.

Many thanks for enabling this on AndroidTV, it's great seeing my pictures on my tv as a slideshow!

**Comment by mvysny** [comment]
Yes, I too find the experience with Android keyboard on Shield horrible. I guess it's Android built-in keyboard so the blame is not really on Shield. The back button which closes the entire screen is extremely infuriating.
Yet, I'm not sure whether there is something I can do - the keyboard is built-in into Android TV and I really don't want to sport out my own keyboard, just because the built-in sucks. Also, you typically go through this painful process just once when you create Samba share - afterwards you no longer need to fight that infernal keyboard anymore.
But maybe this can be improved - you are far more experienced user of Shield (Android TV) than me, so perhaps other apps have a better way of inputting this stuff. Perhaps you can point out an example that would be good to follow?

**Comment by nascentt** [comment]
I only got mine at christmas so am not that experienced i'm afraid, I've
had a low end android tv device for a while but the only app with ui/ux
i've come across that isn't that bad is es file explorer. but it's far from
great.

I guess some quick suggestions: make the control highlight more obvious
when selecting controls by remote, the shadow is very subtle as easy to
miss currently.
make the default of the user creds dialog ok rather than cancel.
remove the second keyboard showing after clicking next when inputting the
share name, i dont understand what this keyboard pops up for as theres
nothing else to enter.
i'll try and find some other advice for this, obviously as you say once you
add the share it's done, but i can see people getting frustrated to the
point of giving up

**Comment by mvysny** [comment]
> first it fails to find the server and points to the wrong ip

That's because the Microsoft's WINS is incompatible with DNS and there is nothing I can do. Nvidia/Google are the ones that should fix their Android configuration.

>  I typed my sharename and press next, then it presents a keyboard again, but I didn't have anything more to type, so I tried pressing back to hide the keyboard and it exited out back to the main screen.

This is a bug in Google's keyboard, actually two bugs: 1. it shouldn't appear when there is nothing focused to input the text to, 2. when pressing the back button only the keyboard should hide and it must not leak the back button press to the underlying activity.

> but the visual highlight when selecting that control is so subtle its hard to know when you're selecting it.

Another Google's mess-up, I'm just using the default Google theme for the buttons which is barely visible. I will implement a workaround since this should be fixable quite easily.

> realised it's because cancel is highlighted by default not done, so when you press finish on the keyboard after entering the credentials it thinks you want the dialog's cancel button so quits.

The default Dialog provided by Google by default shows buttons in that order, and hence makes Cancel as the default option. Another Google mess-up. I am not sure whether this can be changed, I'll investigate.

>  i dont understand what this keyboard pops up for as theres nothing else to enter.

It is because Google's keyboard sucks. Perhaps there is another one in Google Play that's actually working as expected.

It really demotivates me when I need to clean up Google's mess.

**Comment by mvysny** [comment]
I was able to reverse the order of dialog buttons. Also I have made sure that the focus is now clearly visible. Since I can't (and as a matter of principle I don't want to) fix those Google screw-ups, I have done all I could. Marking as fixed in 1.11.1

**Comment by nascentt** [comment]
I appreciate you doing all you can.  Any improvement helps.  Thanks!
