### ISSUE TITLE
Auto start parameter isn't working in Android Box MXQ, android 5.1.

### ISSUE THREAD

**Issue by PauloTVMID** [mvysny/photocloud-frame-slideshow#8]
We are using Android Box MXQ, android version 5.1, on TVs and using the app to advertise some companies. 
I would like the app to launch as soon as the Android Box reboot after being turned on.

**Comment by mvysny** [comment]
Fixed. I have used Handler to delay the boot for 5 seconds, in order for the Wifi to properly start up. However, Android probably killed the app along with the Handler and nothing got done. Now I'm using AlarmManager which is inexact as hell (I say 5 seconds, AlarmManager happily invokes me after 25 seconds) but at least it works.
Fixed in 1.7.33

**Comment by PauloTVMID** [comment]
Well.... it is not working yet....

**Comment by mvysny** [comment]
Can you please obtain the device logs whether photocloud receives the boot-completed event?

**Comment by mvysny** [comment]
I'll by default disable this 5 second timeout. On my phone the BOOT_COMPLETED is delivered lazily, after the wifi is already on. I will however add a configuration setting rgd this.

NOTE: Android will NOT deliver BOOT_COMPLETED to apps which have not been run from the launcher at least once. This is some kind of security precaution, you can read more about that here: http://stackoverflow.com/a/19856367/377320
Anyway, just make sure that you have started PhotoCloud from your phone's launcher at least once.

**Comment by mvysny** [comment]
Fixed in 1.7.34: please head to settings and make sure that:

1. "Auto-start Slideshow on Boot" is enabled
2. "Delay auto-start slideshow on boot" is disabled
3. in "Auto-start Stream List" there is at least one Stream checked.

If that doesn't help, then probably your device doesn't send BOOT_COMPLETED. You can verify that by grabbing your device's log and checking for lines containing *PhotoCloudBoot*. If PhotoCloud receives BOOT_COMPLETED, it will log information with lines like that.
