### ISSUE TITLE
Appending photos to the front of a slideshow?

### ISSUE THREAD

**Issue by djharryg** [mvysny/photocloud-frame-slideshow#95]
Is it possible for a new photo that is added to a Dropbox folder to insert itself into the slideshow and show itself immediately?  And then have the slideshow resume where it left off?

In other words... if I have a slideshow running, and I add a new photo to the folder, can that photo show immediately instead of being placed on the bottom of the slideshow list.

**Comment by mvysny** [comment]
Hi, unfortunately currently that's not possible -currently the entire photo showing cycle needs to end before new photos are picked up. However, the closer the photos are to the root folder, the sooner they will be displayed. So just make sure to place the photos into the root folder and they should be picked soon-ish.

Please let me know if this is enough, or whether you want the new photos to appear immediately. That may however require some kind of notification mechanism from Dropbox about the new photos, and I don't think that Dropbox supports such feature, so it may actually be impossible. But I can check.

**Comment by mvysny** [comment]
Unfortunately this is not possible:

* According to https://stackoverflow.com/questions/17135423/dropbox-api-get-notified-on-file-events-without-polling I should use [Webhooks](https://www.dropbox.com/developers/reference/webhooks) but that's not possible to use with Android apps since they don't expose URL that webhooks can call.
* The Dropbox API jar provides no watcher mechanism
* I could maybe poll root for metadata, hoping that they would change if a file gets uploaded, then traverse the tree to find the possibly added files; however that's hard to implement and would probably be very slow. I can implement it as a custom feature for a bounty only.

Since it's impossible to do in an easy way, closing as won't fix.
